#!/usr/bin/env bash
# ==============================================================================
# aichat-enhance.sh — AIChat Core + LLM-Functions Enhancement Manager v1.0.0
# ==============================================================================
# Safe-by-default updater/extension layer for sigoden/aichat.
#
# Architecture targets:
#   aichat source: src/, Cargo.toml, Argcfile.sh, config.example.yaml
#   runtime data: AICHAT_CONFIG_DIR/{roles,sessions,rags,functions,agents,macros}
#   llm-functions: tools.txt, agents.txt, tools/, agents/, bin/, functions.json
#
# This script intentionally avoids brittle edits to Rust internals. It updates
# the upstream checkout, validates/builds it, installs additive LLM functions,
# roles/macros, and maintains AIChat configuration through supported files/envs.
#
# Usage:
#   ./aichat-enhance.sh install
#   ./aichat-enhance.sh update
#   ./aichat-enhance.sh doctor
#   ./aichat-enhance.sh functions
#   ./aichat-enhance.sh configure
#   ./aichat-enhance.sh all
#
# Options:
#   --repo PATH        AIChat source checkout (default: auto-detect / clone)
#   --functions PATH   llm-functions checkout (default: sibling/auto-detect)
#   --config PATH      AIChat config directory
#   --branch NAME      AIChat git branch (default: main)
#   --dry-run          Show changes without writing
#   --no-build         Do not cargo build
#   --force            Continue past non-fatal validation warnings
#   --backup           Force a backup before changes
# ==============================================================================

set -Eeuo pipefail
IFS=$'\n\t'

VERSION="1.0.0"
REPO_URL="https://github.com/sigoden/aichat.git"
FUNCTIONS_URL="https://github.com/sigoden/llm-functions.git"
BRANCH="main"
REPO=""
FUNCTIONS=""
CONFIG=""
DRY_RUN=0
NO_BUILD=0
FORCE=0
BACKUP=0

C_RESET=$'\033[0m'
C_CYAN=$'\033[38;5;51m'
C_GREEN=$'\033[38;5;46m'
C_RED=$'\033[38;5;196m'
C_YELLOW=$'\033[38;5;226m'
C_PURPLE=$'\033[38;5;129m'
C_PINK=$'\033[38;5;198m'
C_DIM=$'\033[2m'
C_BOLD=$'\033[1m'

say()  { printf '%s\n' "$*" >&2; }
info() { printf '%s[AIChat+]%s %s\n' "$C_CYAN" "$C_RESET" "$*" >&2; }
ok()   { printf '%s[✓]%s %s\n' "$C_GREEN" "$C_RESET" "$*" >&2; }
warn() { printf '%s[!]%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
die()  { printf '%s[✗]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }

trap 'rc=$?; [[ $rc -eq 0 ]] || warn "Failed with exit code $rc at line $LINENO"; exit $rc' EXIT
trap 'warn "Interrupted"; exit 130' INT TERM

usage() {
  cat <<'EOF'
AIChat Enhancement Manager

Commands:
  install      Clone/update repositories and install additive enhancements
  update       Pull AIChat + llm-functions, validate, optionally build
  functions    Install/refresh enhanced local LLM functions
  configure    Create/update supported AIChat configuration and mappings
  doctor       Diagnose source, runtime, tools, configuration and function registry
  backup       Backup AIChat configuration and generated assets
  clean        Remove only assets generated by this script
  all          install + functions + configure + doctor

Options:
  --repo PATH
  --functions PATH
  --config PATH
  --branch NAME
  --dry-run
  --no-build
  --force
  --backup
  -h, --help
EOF
}

while (($#)); do
  case "$1" in
    install|update|functions|configure|doctor|backup|clean|all)
      COMMAND="$1"; shift ;;
    --repo) REPO="${2:?missing path}"; shift 2 ;;
    --functions) FUNCTIONS="${2:?missing path}"; shift 2 ;;
    --config) CONFIG="${2:?missing path}"; shift 2 ;;
    --branch) BRANCH="${2:?missing branch}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --no-build) NO_BUILD=1; shift ;;
    --force) FORCE=1; shift ;;
    --backup) BACKUP=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

COMMAND="${COMMAND:-all}"

have() { command -v "$1" >/dev/null 2>&1; }

run() {
  if ((DRY_RUN)); then
    printf '%s$%s ' "$C_DIM" "$C_RESET" >&2
    printf '%q ' "$@"
    printf '\n' >&2
  else
    "$@"
  fi
}

safe_mkdir() {
  ((DRY_RUN)) || mkdir -p "$1"
}

detect_config() {
  if [[ -n "$CONFIG" ]]; then
    return
  fi

  if [[ -n "${AICHAT_CONFIG_DIR:-}" ]]; then
    CONFIG="$AICHAT_CONFIG_DIR"
    return
  fi

  if have aichat; then
    CONFIG="$(aichat --info 2>/dev/null |
      sed -n 's/^config_dir[[:space:]]*//p' | head -n1 || true)"
    [[ -n "$CONFIG" ]] && return
  fi

  if [[ -n "${XDG_CONFIG_HOME:-}" ]]; then
    CONFIG="$XDG_CONFIG_HOME/aichat"
  elif [[ "$(uname -s 2>/dev/null || true)" == "Darwin" ]]; then
    CONFIG="$HOME/Library/Application Support/aichat"
  else
    CONFIG="$HOME/.config/aichat"
  fi
}

detect_repo() {
  if [[ -n "$REPO" ]]; then return; fi
  if [[ -f "Cargo.toml" && -d "src" ]]; then
    REPO="$PWD"
  elif [[ -d "$HOME/src/aichat/.git" ]]; then
    REPO="$HOME/src/aichat"
  elif [[ -d "$HOME/aichat/.git" ]]; then
    REPO="$HOME/aichat"
  else
    REPO="$HOME/.local/src/aichat"
  fi
}

detect_functions() {
  if [[ -n "$FUNCTIONS" ]]; then return; fi
  if [[ -f "./tools.txt" && -d "./tools" ]]; then
    FUNCTIONS="$PWD"
  elif [[ -d "$HOME/src/llm-functions/.git" ]]; then
    FUNCTIONS="$HOME/src/llm-functions"
  elif [[ -d "$HOME/llm-functions/.git" ]]; then
    FUNCTIONS="$HOME/llm-functions"
  else
    FUNCTIONS="$HOME/.local/src/llm-functions"
  fi
}

require_tools() {
  local missing=()
  local x
  for x in git sed awk grep find mktemp; do
    have "$x" || missing+=("$x")
  done

  if [[ "$COMMAND" == functions || "$COMMAND" == install || "$COMMAND" == all ]]; then
    have argc || missing+=("argc")
    have jq || missing+=("jq")
  fi

  if ((${#missing[@]})); then
    die "Missing required commands: ${missing[*]}"
  fi
}

backup_tree() {
  detect_config
  local stamp backup_dir
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  backup_dir="${CONFIG}.aichat-enhance-backup-${stamp}"

  info "Backing up configuration to $backup_dir"
  if ((DRY_RUN)); then
    say "  would copy: $CONFIG"
    return
  fi

  [[ -d "$CONFIG" ]] || { warn "Config directory does not exist; nothing to back up"; return; }
  cp -a "$CONFIG" "$backup_dir"
  ok "Backup created: $backup_dir"
}

clone_or_update() {
  local dir="$1" url="$2" label="$3"

  if [[ -d "$dir/.git" ]]; then
    info "Updating $label: $dir"
    (
      cd "$dir"
      run git fetch --prune origin
      run git checkout "$BRANCH"
      run git pull --ff-only origin "$BRANCH"
    )
  else
    info "Cloning $label into $dir"
    safe_mkdir "$(dirname "$dir")"
    run git clone --branch "$BRANCH" --depth 1 "$url" "$dir"
  fi
}

validate_aichat_tree() {
  [[ -f "$REPO/Cargo.toml" ]] || return 1
  [[ -d "$REPO/src" ]] || return 1
  [[ -f "$REPO/src/main.rs" ]] || warn "src/main.rs not found; upstream layout may have changed"
  [[ -f "$REPO/src/function.rs" ]] || warn "src/function.rs not found; function architecture may have changed"
  [[ -d "$REPO/src/config" ]] || warn "src/config/ not found"
  [[ -f "$REPO/config.example.yaml" ]] || warn "config.example.yaml not found"
  return 0
}

validate_functions_tree() {
  [[ -d "$FUNCTIONS/tools" ]] || return 1
  [[ -f "$FUNCTIONS/Argcfile.sh" ]] || warn "llm-functions Argcfile.sh missing"
  [[ -f "$FUNCTIONS/tools.txt" ]] || warn "llm-functions tools.txt missing"
  return 0
}

cargo_validate_build() {
  ((NO_BUILD)) && return
  have cargo || { warn "cargo not installed; skipping Rust build"; return; }

  info "Formatting Rust source"
  (cd "$REPO" && run cargo fmt --all)

  info "Checking Rust source"
  (cd "$REPO" && run cargo check --all-targets)

  info "Running tests"
  (cd "$REPO" && run cargo test --all)

  info "Building AIChat"
  (cd "$REPO" && run cargo build --release)

  ok "AIChat source validated and built"
}

write_file() {
  local path="$1"
  if ((DRY_RUN)); then
    info "Would write $path"
    return
  fi
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

install_tool_system_info() {
  local p="$FUNCTIONS/tools/aichat_system_info.py"
  write_file "$p" <<'PY'
#!/usr/bin/env python3
"""Return compact, non-secret local runtime information for AIChat."""
import json
import os
import platform
import shutil
import sys

def run(include_env: bool = False):
    """Inspect the local runtime without exposing secrets.
    Args:
        include_env: Include a small allowlist of useful AIChat environment settings.
    """
    result = {
        "platform": platform.platform(),
        "system": platform.system(),
        "release": platform.release(),
        "machine": platform.machine(),
        "python": platform.python_version(),
        "shell": os.environ.get("SHELL", ""),
        "termux": os.path.exists("/data/data/com.termux"),
        "commands": {
            name: bool(shutil.which(name))
            for name in ("aichat", "argc", "jq", "git", "cargo", "curl")
        },
    }
    if include_env:
        allow = (
            "AICHAT_CONFIG_DIR",
            "AICHAT_FUNCTIONS_DIR",
            "AICHAT_MODEL",
            "AICHAT_LIGHT_THEME",
        )
        result["env"] = {k: os.environ[k] for k in allow if k in os.environ}
    return result

if __name__ == "__main__":
    print(json.dumps(run(False), indent=2))
PY
  ((DRY_RUN)) || chmod +x "$p"
}

install_tool_json_query() {
  local p="$FUNCTIONS/tools/aichat_json_query.py"
  write_file "$p" <<'PY'
#!/usr/bin/env python3
"""Safely query JSON from stdin or a supplied file using jq."""
import json
import subprocess

def run(expression: str, path: str = ""):
    """Run a read-only jq expression.
    Args:
        expression: jq expression, such as '.items[] | .name'.
        path: Optional JSON file to read instead of stdin.
    """
    source = open(path, encoding="utf-8").read() if path else __import__("sys").stdin.read()
    try:
        json.loads(source)
    except json.JSONDecodeError as exc:
        return {"success": False, "error": f"invalid JSON: {exc}"}
    proc = subprocess.run(
        ["jq", "-c", expression],
        input=source,
        text=True,
        capture_output=True,
        timeout=15,
        check=False,
    )
    return {
        "success": proc.returncode == 0,
        "output": proc.stdout.strip(),
        "error": proc.stderr.strip(),
        "exit_code": proc.returncode,
    }
PY
  ((DRY_RUN)) || chmod +x "$p"
}

install_tool_git_summary() {
  local p="$FUNCTIONS/tools/aichat_git_summary.sh"
  write_file "$p" <<'SH'
#!/usr/bin/env bash
set -euo pipefail

# @describe Return a compact read-only Git repository summary.
# @option --path! Repository path.
# @option --limit Number of recent commits to return (default: 8).

main() {
  local path="${argc_path}"
  local limit="${argc_limit:-8}"

  [[ -d "$path/.git" ]] || {
    printf '{"success":false,"error":"Not a Git repository: %s"}\n' "$path"
    return 1
  }

  git -C "$path" status --short --branch
  printf '\n--- recent commits ---\n'
  git -C "$path" log -n "$limit" --date=short \
    --pretty=format:'%h | %ad | %an | %s'
}

eval "$(argc --argc-eval "$0" "$@")"
SH
  ((DRY_RUN)) || chmod +x "$p"
}

install_tool_aichat_info() {
  local p="$FUNCTIONS/tools/aichat_info.sh"
  write_file "$p" <<'SH'
#!/usr/bin/env bash
set -euo pipefail

# @describe Inspect the local AIChat installation and supported runtime paths.
# @flag --verbose Include complete aichat --info output.

main() {
  command -v aichat >/dev/null 2>&1 || {
    printf '{"success":false,"error":"aichat executable not found"}\n'
    return 1
  }

  if [[ -n "${argc_verbose:-}" ]]; then
    aichat --info
  else
    aichat --info | sed -n \
      -e '/^version[[:space:]]/p' \
      -e '/^config_file[[:space:]]/p' \
      -e '/^config_dir[[:space:]]/p' \
      -e '/^functions_dir[[:space:]]/p' \
      -e '/^data_dir[[:space:]]/p'
  fi
}

eval "$(argc --argc-eval "$0" "$@")"
SH
  ((DRY_RUN)) || chmod +x "$p"
}

install_tools() {
  info "Installing additive AIChat tools into $FUNCTIONS/tools"
  safe_mkdir "$FUNCTIONS/tools"

  install_tool_system_info
  install_tool_json_query
  install_tool_git_summary
  install_tool_aichat_info

  if [[ -f "$FUNCTIONS/tools.txt" ]]; then
    local t
    for t in \
      aichat_system_info.py \
      aichat_json_query.py \
      aichat_git_summary.sh \
      aichat_info.sh
    do
      grep -qxF "$t" "$FUNCTIONS/tools.txt" || {
        if ((DRY_RUN)); then
          info "Would add $t to tools.txt"
        else
          printf '%s\n' "$t" >> "$FUNCTIONS/tools.txt"
        fi
      }
    done
  else
    write_file "$FUNCTIONS/tools.txt" <<'EOF'
aichat_system_info.py
aichat_json_query.py
aichat_git_summary.sh
aichat_info.sh
EOF
  fi

  if have argc && [[ -f "$FUNCTIONS/Argcfile.sh" ]]; then
    info "Rebuilding llm-functions registry"
    (cd "$FUNCTIONS" && run argc build)
    (cd "$FUNCTIONS" && run argc check) || {
      ((FORCE)) || die "llm-functions check failed"
      warn "llm-functions check failed; --force allows continuation"
    }
  fi

  ok "LLM functions installed"
}

write_roles() {
  safe_mkdir "$CONFIG/roles"

  write_file "$CONFIG/roles/toolsmith.md" <<'EOF'
---
name: toolsmith
model: null
temperature: null
---

You are an AIChat toolsmith.

Prefer available function tools over inventing commands.
Inspect before modifying.
For filesystem operations, explain the target and intended effect.
Do not expose API keys, tokens, cookies, or private environment variables.
When a tool fails, diagnose the concrete error and propose the smallest recovery.
Return concise, structured results suitable for a terminal workflow.
EOF

  write_file "$CONFIG/roles/sysadmin.md" <<'EOF'
---
name: sysadmin
model: null
temperature: null
---

You are a cautious local systems assistant.

Use read-only inspection first.
Never delete, overwrite, install, or execute privileged operations unless explicitly requested.
Prefer reproducible commands.
Detect Termux, Linux, macOS, and Windows differences before suggesting platform-specific commands.
Report commands, paths, and assumptions clearly.
EOF
}

write_macros() {
  safe_mkdir "$CONFIG/macros"

  write_file "$CONFIG/macros/ai-doctor.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

printf '\033[38;5;51m╭─ AIChat Doctor ─────────────────────────────╮\033[0m\n'

if command -v aichat >/dev/null 2>&1; then
  aichat --info 2>&1 | sed -n \
    -e '/^version[[:space:]]/p' \
    -e '/^config_file[[:space:]]/p' \
    -e '/^config_dir[[:space:]]/p' \
    -e '/^functions_dir[[:space:]]/p' \
    -e '/^data_dir[[:space:]]/p'
else
  printf 'aichat: NOT FOUND\n'
fi

for x in argc jq git cargo python3; do
  if command -v "$x" >/dev/null 2>&1; then
    printf '%-10s OK\n' "$x"
  else
    printf '%-10s MISSING\n' "$x"
  fi
done

printf '\033[38;5;51m╰──────────────────────────────────────────────╯\033[0m\n'
EOF
  ((DRY_RUN)) || chmod +x "$CONFIG/macros/ai-doctor.sh"
}

configure_aichat() {
  detect_config
  safe_mkdir "$CONFIG"

  local cfg="$CONFIG/config.yaml"

  if [[ -f "$cfg" ]]; then
    info "Existing config preserved: $cfg"
  else
    write_file "$cfg" <<'EOF'
# AIChat+ managed configuration.
# Review provider/model values before first use.

function_calling: true

mapping_tools:
  local: 'aichat_system_info,aichat_json_query,aichat_git_summary,aichat_info'

use_tools: 'local'

stream: true
save: true
highlight: true
wrap: auto
wrap_code: false
EOF
  fi

  # Additive, idempotent configuration snippets. Do not rewrite existing values.
  if ! grep -q '^function_calling:' "$cfg"; then
    printf '\nfunction_calling: true\n' >> "$cfg"
  fi

  if ! grep -q '^mapping_tools:' "$cfg"; then
    cat >> "$cfg" <<'EOF'

mapping_tools:
  local: 'aichat_system_info,aichat_json_query,aichat_git_summary,aichat_info'
EOF
  elif ! grep -q '^[[:space:]]*local:' "$cfg"; then
    cat >> "$cfg" <<'EOF'
  local: 'aichat_system_info,aichat_json_query,aichat_git_summary,aichat_info'
EOF
  fi

  if ! grep -q '^use_tools:' "$cfg"; then
    printf '\nuse_tools: local\n' >> "$cfg"
  fi

  write_roles
  write_macros
  ok "AIChat runtime configuration enhanced"
}

link_functions_to_aichat() {
  detect_config
  local target

  if have aichat; then
    target="$(aichat --info 2>/dev/null |
      sed -n 's/^functions_dir[[:space:]]*//p' | head -n1 || true)"
  fi

  if [[ -z "${target:-}" ]]; then
    target="$CONFIG/functions"
  fi

  if [[ "$target" == "$FUNCTIONS" ]]; then
    ok "LLM-functions already selected as functions directory"
    return
  fi

  safe_mkdir "$(dirname "$target")"

  if [[ -e "$target" || -L "$target" ]]; then
    if [[ -L "$target" ]]; then
      local current
      current="$(readlink "$target" || true)"
      if [[ "$current" == "$FUNCTIONS" ]]; then
        ok "AIChat functions symlink already correct"
        return
      fi
    fi
    warn "AIChat functions path already exists: $target"
    warn "Not replacing it automatically"
    return
  fi

  info "Linking llm-functions to AIChat: $target -> $FUNCTIONS"
  run ln -s "$FUNCTIONS" "$target"
  ok "Function directory linked"
}

doctor() {
  detect_repo
  detect_functions
  detect_config

  local failures=0

  printf '%s╭─ AIChat+ Doctor v%s ─────────────────────────────╮%s\n' "$C_PURPLE" "$VERSION" "$C_RESET"
  printf '  AIChat source : %s\n' "$REPO"
  printf '  Functions     : %s\n' "$FUNCTIONS"
  printf '  Config        : %s\n' "$CONFIG"

  if validate_aichat_tree; then ok "AIChat source tree"; else warn "AIChat source tree incomplete"; failures=$((failures+1)); fi
  if validate_functions_tree; then ok "llm-functions tree"; else warn "llm-functions tree incomplete"; failures=$((failures+1)); fi

  for x in aichat argc jq git cargo python3; do
    if have "$x"; then
      printf '  %-12s %sOK%s\n' "$x" "$C_GREEN" "$C_RESET"
    else
      printf '  %-12s %sMISSING%s\n' "$x" "$C_RED" "$C_RESET"
      failures=$((failures+1))
    fi
  done

  if [[ -f "$CONFIG/config.yaml" ]]; then
    ok "config.yaml present"
    if grep -q '^function_calling:[[:space:]]*true' "$CONFIG/config.yaml"; then
      ok "function calling enabled"
    else
      warn "function_calling is not explicitly enabled"
    fi
  else
    warn "config.yaml missing"
  fi

  if [[ -f "$FUNCTIONS/functions.json" ]]; then
    ok "functions.json present"
    if have jq && jq empty "$FUNCTIONS/functions.json" >/dev/null 2>&1; then
      ok "functions.json is valid JSON"
    else
      warn "functions.json is invalid"
      failures=$((failures+1))
    fi
  else
    warn "functions.json missing; run argc build in llm-functions"
  fi

  if have aichat; then
    printf '\n%sAIChat info:%s\n' "$C_CYAN" "$C_RESET"
    aichat --info 2>/dev/null || true
  fi

  printf '%s╰──────────────────────────────────────────────────╯%s\n' "$C_PURPLE" "$C_RESET"
  ((failures == 0)) || ((FORCE)) || return 1
}

clean_generated() {
  detect_config
  detect_functions

  warn "This removes only assets generated by this script."
  if ((DRY_RUN)); then
    say "Would remove:"
    say "  $CONFIG/roles/toolsmith.md"
    say "  $CONFIG/roles/sysadmin.md"
    say "  $CONFIG/macros/ai-doctor.sh"
    say "  $FUNCTIONS/tools/aichat_system_info.py"
    say "  $FUNCTIONS/tools/aichat_json_query.py"
    say "  $FUNCTIONS/tools/aichat_git_summary.sh"
    say "  $FUNCTIONS/tools/aichat_info.sh"
    return
  fi

  rm -f \
    "$CONFIG/roles/toolsmith.md" \
    "$CONFIG/roles/sysadmin.md" \
    "$CONFIG/macros/ai-doctor.sh" \
    "$FUNCTIONS/tools/aichat_system_info.py" \
    "$FUNCTIONS/tools/aichat_json_query.py" \
    "$FUNCTIONS/tools/aichat_git_summary.sh" \
    "$FUNCTIONS/tools/aichat_info.sh"

  ok "Generated assets removed"
}

install() {
  detect_repo
  detect_functions
  detect_config
  require_tools

  [[ -d "$REPO/.git" ]] || clone_or_update "$REPO" "$REPO_URL" "AIChat"
  [[ -d "$FUNCTIONS/.git" ]] || clone_or_update "$FUNCTIONS" "$FUNCTIONS_URL" "llm-functions"

  validate_aichat_tree || die "Invalid AIChat checkout: $REPO"
  validate_functions_tree || die "Invalid llm-functions checkout: $FUNCTIONS"

  if ((BACKUP)); then backup_tree; fi

  cargo_validate_build
  install_tools
  configure_aichat
  link_functions_to_aichat
}

update() {
  detect_repo
  detect_functions

  [[ -d "$REPO/.git" ]] || clone_or_update "$REPO" "$REPO_URL" "AIChat"
  [[ -d "$FUNCTIONS/.git" ]] || clone_or_update "$FUNCTIONS" "$FUNCTIONS_URL" "llm-functions"

  validate_aichat_tree || die "Invalid AIChat checkout"
  validate_functions_tree || die "Invalid llm-functions checkout"

  if ((BACKUP)); then backup_tree; fi

  (
    cd "$REPO"
    info "Refreshing Cargo dependencies"
    run cargo update
  )

  cargo_validate_build

  (
    cd "$FUNCTIONS"
    info "Refreshing LLM-functions"
    run git fetch --prune origin
    run git checkout "$BRANCH"
    run git pull --ff-only origin "$BRANCH"
    run argc build
    run argc check
  )
}

main() {
  detect_repo
  detect_functions
  detect_config

  case "$COMMAND" in
    install)   install ;;
    update)    update ;;
    functions) require_tools; install_tools; link_functions_to_aichat ;;
    configure) configure_aichat ;;
    doctor)    doctor ;;
    backup)    backup_tree ;;
    clean)     clean_generated ;;
    all)
      BACKUP=1
      install
      doctor
      ;;
    *) die "Unknown command: $COMMAND" ;;
  esac

  ok "AIChat+ operation '$COMMAND' complete"
}

main "$@"
