#!/usr/bin/env python3
# ==============================================================================
# cheat_sheet_gen.py — Interactive Cheat Sheet Generator v1.0.0
# argc/aichat compatible · Termux · Markdown/HTML/PDF cheat sheet creation
#
# @describe Generate interactive cheat sheets for commands, tools, and references
#
# @meta require-tools aichat
#
# @option --title! <STRING>              Cheat sheet title (required)
# @option --category <STRING>            Category/tag for the cheat sheet (default: general)
# @option --format <STRING>              Output format: md, html, pdf, json (default: md)
# @option --output <PATH>                Output file path (default: ./cheatsheet.{format})
# @option --template <PATH>              Custom template file path
# @option --author <STRING>              Author name for the cheat sheet
# @option --version <STRING>             Version number (default: 1.0.0)
# @option --columns <INTEGER>            Number of columns for layout (default: 2)
# @option --max-width <INTEGER>          Maximum width in characters (default: 80)
# @flag   --include-toc                  Include table of contents
# @flag   --number-sections              Number sections automatically
# @flag   --highlight-syntax             Enable syntax highlighting for code blocks
# @flag   --compact                      Use compact layout (less whitespace)
# @flag   --verbose                      Show detailed processing information
# @flag   --no-color                     Disable ANSI colour output
#
# @env LLM_OUTPUT=/dev/stdout            Output path for LLM integration
# @env CHEAT_SHEET_DIR=/data/data/com.termux/files/home/.config/aichat/cheat_sheets  Default cheat sheet directory
# @env CHEAT_SHEET_TEMPLATE_DIR=/data/data/com.termux/files/home/.config/aichat/cheat_sheet_templates  Template directory
# ==============================================================================

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
import textwrap
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

# Colorama initialization for cross-platform colored output
import colorama
from colorama import Fore, Style, Back

colorama.init(autoreset=True)

# Version information
__version__ = "1.0.0"
__author__ = "aichat/argc Tool Suite"
__description__ = "Interactive Cheat Sheet Generator"

# Default directories
DEFAULT_CHEAT_SHEET_DIR = Path(os.environ.get(
    "CHEAT_SHEET_DIR", 
    "/data/data/com.termux/files/home/.config/aichat/cheat_sheets"
))
DEFAULT_TEMPLATE_DIR = Path(os.environ.get(
    "CHEAT_SHEET_TEMPLATE_DIR", 
    "/data/data/com.termux/files/home/.config/aichat/cheat_sheet_templates"
))

# Supported formats
SUPPORTED_FORMATS = {"md": "markdown", "html": "html", "pdf": "pdf", "json": "json"}
DEFAULT_FORMAT = "md"

# Default template
DEFAULT_TEMPLATE = """# {title}

*Generated by {author} on {date}*
*Category: {category} | Version: {version}*

{content}

---
*This cheat sheet was generated using cheat_sheet_gen v{tool_version}*
"""

class CheatSheetGenerator:
    """Main cheat sheet generator class."""
    
    def __init__(self, args: argparse.Namespace):
        self.args = args
        self.title = args.title
        self.category = args.category or "general"
        self.format = args.format.lower() if args.format else DEFAULT_FORMAT
        self.output_path = Path(args.output) if args.output else None
        self.template_path = Path(args.template) if args.template else None
        self.author = args.author or __author__
        self.version = args.version or "1.0.0"
        self.columns = args.columns or 2
        self.max_width = args.max_width or 80
        self.include_toc = args.include_toc
        self.number_sections = args.number_sections
        self.highlight_syntax = args.highlight_syntax
        self.compact = args.compact
        self.verbose = args.verbose
        self.no_color = args.no_color
        
        # Validate format
        if self.format not in SUPPORTED_FORMATS:
            self._error(f"Unsupported format: {self.format}. Supported: {', '.join(SUPPORTED_FORMATS.keys())}")
            
        # Setup directories
        self.cheat_sheet_dir = DEFAULT_CHEAT_SHEET_DIR
        self.template_dir = DEFAULT_TEMPLATE_DIR
        self.cheat_sheet_dir.mkdir(parents=True, exist_ok=True)
        self.template_dir.mkdir(parents=True, exist_ok=True)
        
        # Initialize content
        self.sections: List[Dict[str, Any]] = []
        self.metadata = {
            "title": self.title,
            "category": self.category,
            "author": self.author,
            "version": self.version,
            "created": datetime.now().isoformat(),
            "tool_version": __version__
        }
    
    def _error(self, message: str) -> None:
        """Display error message and exit."""
        if not self.no_color:
            print(f"{Fore.RED}Error: {message}{Style.RESET_ALL}", file=sys.stderr)
        else:
            print(f"Error: {message}", file=sys.stderr)
        sys.exit(1)
    
    def _info(self, message: str) -> None:
        """Display info message if verbose."""
        if self.verbose:
            if not self.no_color:
                print(f"{Fore.BLUE}Info: {message}{Style.RESET_ALL}")
            else:
                print(f"Info: {message}")
    
    def _success(self, message: str) -> None:
        """Display success message."""
        if not self.no_color:
            print(f"{Fore.GREEN}Success: {message}{Style.RESET_ALL}")
        else:
            print(f"Success: {message}")
    
    def add_section(self, title: str, content: str, subsection: bool = False) -> None:
        """Add a section to the cheat sheet."""
        section = {
            "title": title,
            "content": content,
            "subsection": subsection,
            "level": 2 if subsection else 1
        }
        self.sections.append(section)
        self._info(f"Added section: {title}")
    
    def add_code_block(self, language: str, code: str) -> str:
        """Format a code block for the specified format."""
        if self.format == "md":
            if self.highlight_syntax:
                return f"```{language}\n{code}\n```"
            else:
                return f"```\n{code}\n```"
        elif self.format == "html":
            # Simple HTML formatting for code
            escaped_code = code.replace("&", "&").replace("<", "<").replace(">", ">")
            return f'<pre><code class="language-{language}">{escaped_code}</code></pre>'
        elif self.format == "json":
            return json.dumps({"type": "code_block", "language": language, "content": code})
        else:  # pdf or fallback
            return f"```{language}\n{code}\n```"
    
    def add_table(self, headers: List[str], rows: List[List[str]]) -> str:
        """Create a formatted table."""
        if self.format == "md":
            # Markdown table
            header_line = "| " + " | ".join(headers) + " |"
            separator_line = "|" + "|".join([" --- " for _ in headers]) + "|"
            rows_lines = []
            for row in rows:
                rows_lines.append("| " + " | ".join(row) + " |")
            return "\n".join([header_line, separator_line] + rows_lines)
        elif self.format == "html":
            # HTML table
            html = "<table>\n<thead>\n<tr>"
            html += "".join([f"<th>{h}</th>" for h in headers])
            html += "</tr>\n</thead>\n<tbody>\n"
            for row in rows:
                html += "<tr>"
                html += "".join([f"<td>{cell}</td>" for cell in row])
                html += "</tr>\n"
            html += "</tbody>\n</table>"
            return html
        else:
            # Simple text table for other formats
            lines = []
            lines.append(" | ".join(headers))
            lines.append("-" * (len(" | ".join(headers))))
            for row in rows:
                lines.append(" | ".join(row))
            return "\n".join(lines)
    
    def generate_content(self) -> str:
        """Generate the main content from sections."""
        if not self.sections:
            return "*No content added to cheat sheet yet.*"
        
        content_parts = []
        
        for i, section in enumerate(self.sections):
            level = section["level"]
            title = section["title"]
            content = section["content"]
            
            # Add section header
            if self.format == "md":
                prefix = "#" * level
                content_parts.append(f"{prefix} {title}\n")
                content_parts.append(content)
                content_parts.append("")  # Blank line
            elif self.format == "html":
                content_parts.append(f"<h{level}>{title}</h{level}>\n")
                content_parts.append(f"<p>{content}</p>\n")
            elif self.format == "json":
                # JSON structure will be handled separately
                pass
            else:
                # Plain text format
                content_parts.append(f"{title}\n")
                content_parts.append("=" * len(title) + "\n")
                content_parts.append(content + "\n\n")
        
        if self.format == "json":
            # Build JSON structure
            result = {
                "metadata": self.metadata,
                "sections": self.sections
            }
            return json.dumps(result, indent=2)
        else:
            return "\n".join(content_parts)
    
    def apply_template(self, content: str) -> str:
        """Apply template to content."""
        if self.template_path and self.template_path.exists():
            try:
                template_content = self.template_path.read_text(encoding="utf-8")
                self._info(f"Using custom template: {self.template_path}")
            except Exception as e:
                self._error(f"Failed to read template file: {e}")
        else:
            template_content = DEFAULT_TEMPLATE
            self._info("Using default template")
        
        # Replace template variables
        replacements = {
            "{title}": self.title,
            "{author}": self.author,
            "{date}": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "{category}": self.category,
            "{version}": self.version,
            "{content}": content,
            "{tool_version}": __version__
        }
        
        result = template_content
        for placeholder, value in replacements.items():
            result = result.replace(placeholder, str(value))
        
        return result
    
    def save_output(self, content: str) -> Path:
        """Save the generated cheat sheet to file."""
        if self.output_path:
            output_file = self.output_path
        else:
            # Generate default filename
            safe_title = re.sub(r'[^\w\s-]', '', self.title).strip().lower()
            safe_title = re.sub(r'[-\s]+', '-', safe_title)
            if not safe_title:
                safe_title = "cheatsheet"
            output_file = self.cheat_sheet_dir / f"{safe_title}.{self.format}"
        
        try:
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text(content, encoding="utf-8")
            self._success(f"Cheat sheet saved to: {output_file}")
            return output_file
        except Exception as e:
            self._error(f"Failed to save cheat sheet: {e}")
    
    def generate(self) -> Path:
        """Main generation method."""
        self._info(f"Generating cheat sheet: {self.title}")
        self._info(f"Format: {self.format}, Category: {self.category}")
        
        # Generate content
        content = self.generate_content()
        self._info("Content generated")
        
        # Apply template
        final_content = self.apply_template(content)
        self._info("Template applied")
        
        # Save output
        output_file = self.save_output(final_content)
        
        return output_file

def run(**kwargs) -> None:
    """Entry point for argc/aichat - accepts keyword arguments from wrapper."""
    # Convert kwargs to argparse.Namespace for compatibility with existing code
    import argparse
    args = argparse.Namespace()
    for key, value in kwargs.items():
        setattr(args, key, value)
    
    # Handle boolean flags that might be missing
    if not hasattr(args, 'include_toc'):
        args.include_toc = False
    if not hasattr(args, 'number_sections'):
        args.number_sections = False
    if not hasattr(args, 'highlight_syntax'):
        args.highlight_syntax = False
    if not hasattr(args, 'compact'):
        args.compact = False
    if not hasattr(args, 'verbose'):
        args.verbose = False
    if not hasattr(args, 'no_color'):
        args.no_color = False
    
    generator = CheatSheetGenerator(args)
    output_file = generator.generate()
    
    if not args.no_color:
        print(f"{Fore.CYAN}Generated cheat sheet: {output_file}{Style.RESET_ALL}")
    else:
        print(f"Generated cheat sheet: {output_file}")

def main() -> None:
    """Main entry point for direct execution."""
    parser = argparse.ArgumentParser(
        description="Generate interactive cheat sheets for commands, tools, and references",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  cheat_sheet_gen.py --title "Python Basics" --format md
  cheat_sheet_gen.py --title "Git Commands" --category dev --format html --output ./git.html
  cheat_sheet_gen.py --title "Linux Terminal" --format md --include-toc --number-sections

For more information, visit: https://github.com/aichat/argc-tool-suite
        """
    )
    
    # Required arguments
    parser.add_argument("--title", required=True, help="Cheat sheet title (required)")
    
    # Optional arguments
    parser.add_argument("--category", help="Category/tag for the cheat sheet (default: general)")
    parser.add_argument("--format", help=f"Output format: {', '.join(SUPPORTED_FORMATS.keys())} (default: md)")
    parser.add_argument("--output", help="Output file path (default: ./cheatsheet.{format})")
    parser.add_argument("--template", help="Custom template file path")
    parser.add_argument("--author", help="Author name for the cheat sheet")
    parser.add_argument("--version", help="Version number (default: 1.0.0)")
    parser.add_argument("--columns", type=int, help="Number of columns for layout (default: 2)")
    parser.add_argument("--max-width", type=int, help="Maximum width in characters (default: 80)")
    
    # Flags
    parser.add_argument("--include-toc", action="store_true", help="Include table of contents")
    parser.add_argument("--number-sections", action="store_true", help="Number sections automatically")
    parser.add_argument("--highlight-syntax", action="store_true", help="Enable syntax highlighting for code blocks")
    parser.add_argument("--compact", action="store_true", help="Use compact layout (less whitespace)")
    parser.add_argument("--verbose", action="store_true", help="Show detailed processing information")
    parser.add_argument("--no-color", action="store_true", help="Disable ANSI colour output")
    
    args = parser.parse_args()
    
    try:
        generator = CheatSheetGenerator(args)
        output_file = generator.generate()
        
        if not args.no_color:
            print(f"{Fore.CYAN}Generated cheat sheet: {output_file}{Style.RESET_ALL}")
        else:
            print(f"Generated cheat sheet: {output_file}")
            
    except KeyboardInterrupt:
        print("\\nGeneration cancelled by user.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        if not args.no_color:
            print(f"{Fore.RED}Unexpected error: {e}{Style.RESET_ALL}", file=sys.stderr)
        else:
            print(f"Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
